### ISSUE TITLE
[DevOnly] Calling setPower cause this

### ISSUE THREAD

**Issue by aodzip** [ImagicalCorp/ImagicalMine#261]
[07:56:38] [NOTICE]: InvalidStateException: "Accessing static property pocketmine\block\WoodenButton::$power as non static" (E_STRICT) in "/src/pocketmine/block/Block" at line 977

EDIT: One Line Is Enough

**Comment by legoboy0215** [comment]
I think it is fixed.

**Comment by aodzip** [comment]
no , i use private function setPower
the setPower in block/Block.php still buggy

**Comment by thebigsmileXD** [comment]
Thats true Legoboy. But you can't know because you havent worked on the redstone.

@aodzip its because its a static property which you cant change.. I'll have a look at it today, i have holliday
