### ISSUE TITLE
Crash with Error: Undefined index: pocketmine\entity\ThrownPotion

### ISSUE THREAD

**Issue by ecoron** [ImagicalCorp/ImagicalMine#473]
since build 259 i notice this error:

```
Error: Undefined index: pocketmine\entity\ThrownPotion
File: /src/pocketmine/entity/Entity
Line: 556
Type: notice

Code:
[547]           return false;
[548]   }
[549]
[550]   /**
[551]    * Returns the short save name
[552]    *
[553]    * @return string
[554]    */
[555]   public function getSaveId(){
[556]           return self::$shortNames[static::class];
[557]   }
[558]
[559]   public function saveNBT(){
[560]           if(!($this instanceof Player)){
[561]                   $this->namedtag->id = new String("id", $this->getSaveId());
[562]                   if($this->getNameTag() !== ""){
[563]                           $this->namedtag->CustomName = new String("CustomName", $this->getNameTag());
[564]                           $this->namedtag->CustomNameVisible = new String("CustomNameVisible", $this->isNameTagVisible());
[565]                   }else{
[566]                           unset($this->namedtag->CustomName);

Backtrace:
#0 /src/pocketmine/entity/Entity(561): pocketmine\entity\Entity->getSaveId(boolean)
#1 /src/pocketmine/entity/Projectile(82): pocketmine\entity\Entity->saveNBT(boolean)
#2 /src/pocketmine/level/format/mcregion/Chunk(403): pocketmine\entity\Projectile->saveNBT(boolean)
#3 /src/pocketmine/level/format/mcregion/RegionLoader(173): pocketmine\level\format\mcregion\Chunk->toBinary(boolean)
#4 /src/pocketmine/level/format/mcregion/McRegion(248): pocketmine\level\format\mcregion\RegionLoader->writeChunk(pocketmine\level\format\mcr$
#5 /src/pocketmine/level/Level(1066): pocketmine\level\format\mcregion\McRegion->saveChunk(integer -49, integer -124)
#6 /src/pocketmine/level/Level(1054): pocketmine\level\Level->saveChunks(boolean)
#7 /src/pocketmine/Server(2406): pocketmine\level\Level->save(boolean )
#8 /src/pocketmine/Server(2550): pocketmine\Server->doAutoSave(boolean)
#9 /src/pocketmine/Server(2243): pocketmine\Server->tick(boolean)
#10 /src/pocketmine/Server(2121): pocketmine\Server->tickProcessor(boolean)
#11 /src/pocketmine/Server(1722): pocketmine\Server->start(boolean)
```

**Comment by thebigsmileXD** [comment]
Confirmed.. @PeratX Any idea?

**Comment by kam187** [comment]
When does this happen?  How can i reproduce it?

**Comment by matcracker** [comment]
When you launch splash potion or exp bottle in this case...

**Comment by kam187** [comment]
Hmm i tried it but i don't get the error with the latest code.  Does it happen every time?

**Comment by thebigsmileXD** [comment]
I thought this was fixed for ExpBottles. And no, it happens randomly.. In my case i threw ExpBottles at my gf

**Comment by PeratX** [comment]
@thebigsmileXD Well,you forgot to registerEntity in Server.php

**Comment by thebigsmileXD** [comment]
Ah i see, thanks

**Comment by BlackShadow1** [comment]
Is fixed?

**Comment by thebigsmileXD** [comment]
Yes
