### ISSUE TITLE
Crash on build #512

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/ImagicalMine#665]
![screenshot_2016-01-19-10-18-50 01](https://cloud.githubusercontent.com/assets/15706847/12413281/5573a762-be96-11e5-83a3-f5d2fd73a710.png)

**Comment by robske110** [comment]
Fixed now

**Comment by dterweij** [comment]
Not much info. When did it happen and what where you doing in your world. Could be a corrupted thing in your world. Still happening? if not then close the issue until it happens again with more details.
